#ifndef _ALTERA_MASTER_FIFO_SC_H_
#define _ALTERA_MASTER_FIFO_SC_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '../../../CODE_qsys/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'master_fifo_sc' and devices
 * connected to the following master:
 *   master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'adc_fifo_sc', class 'altera_avalon_sc_fifo'
 * The macros are prefixed with 'ADC_FIFO_SC_'.
 * The prefix is the slave descriptor.
 */
#define ADC_FIFO_SC_COMPONENT_TYPE altera_avalon_sc_fifo
#define ADC_FIFO_SC_COMPONENT_NAME adc_fifo_sc
#define ADC_FIFO_SC_BASE 0x0
#define ADC_FIFO_SC_SPAN 16
#define ADC_FIFO_SC_END 0xf


#endif /* _ALTERA_MASTER_FIFO_SC_H_ */
